import 'package:flutter/material.dart';

final ThemeData darkyy = ThemeData(
  useMaterial3: true,
  applyElevationOverlayColor: true,
  brightness: Brightness.dark,
  canvasColor: const Color(0xFF10140F),
  cardColor: const Color(0xFF10140F),
  dialogBackgroundColor: const Color(0xFF10140F),
  disabledColor: const Color(0x62FFFFFF),
  dividerColor: const Color(0x1FE0E4DB),
  focusColor: const Color(0x1FFFFFFF),
  highlightColor: const Color(0x40CCCCCC),
  hintColor: const Color(0x99FFFFFF),
  hoverColor: const Color(0x0AFFFFFF),
  iconTheme: const IconThemeData(color: Color(0xFFFFFFFF)),
  indicatorColor: const Color(0xFFE0E4DB),
  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
  platform: TargetPlatform.linux,
  primaryColor: const Color(0xFF10140F),
  primaryColorDark: const Color(0xFF000000),
  primaryColorLight: const Color(0xFF9E9E9E),
  primaryIconTheme: const IconThemeData(color: Color(0xFFFFFFFF)),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    type: BottomNavigationBarType.fixed,
    unselectedItemColor: Colors.grey,
    selectedItemColor: Color(0xFFA1D39A),
  ),
  buttonTheme: ButtonThemeData(
    alignedDropdown: false,
    colorScheme: const ColorScheme.dark(
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      inversePrimary: Color(0xFF3B6939),
      inverseSurface: Color(0xFFE0E4DB),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      onInverseSurface: Color(0xFF2D322C),
      onPrimary: Color(0xFF0A390F),
      onPrimaryContainer: Color(0xFFBCF0B4),
      onSecondary: Color(0xFF253423),
      onSecondaryContainer: Color(0xFFD5E8CF),
      onSurface: Color(0xFFE0E4DB),
      onSurfaceVariant: Color(0xFFC2C9BD),
      onTertiary: Color(0xFF00363B),
      onTertiaryContainer: Color(0xFFBCEBF0),
      outline: Color(0xFF8C9388),
      outlineVariant: Color(0xFF424940),
      primary: Color(0xFFA1D39A),
      primaryContainer: Color(0xFF235024),
      scrim: Color(0xFF000000),
      secondary: Color(0xffbaccb3),
      secondaryContainer: Color(0xFF3B4B38),
      shadow: Color(0xFF000000),
      surface: Color(0xFF10140F),
      surfaceContainerHighest: Color(0xFF323630),
      surfaceTint: Color(0xFFA1D39A),
      tertiary: Color(0xFFA0CFD4),
      tertiaryContainer: Color(0xFF1F4D52),
    ),
    height: 36,
    layoutBehavior: ButtonBarLayoutBehavior.padded,
    minWidth: 88,
    padding: const EdgeInsets.symmetric(horizontal: 16),
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(2),
      side: const BorderSide(
        color: Color(0xFF000000),
        width: 0,
        style: BorderStyle.none,
      ),
    ),
  ),
  colorScheme: const ColorScheme.dark(
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    inversePrimary: Color(0xFF3B6939),
    inverseSurface: Color(0xFFE0E4DB),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    onInverseSurface: Color(0xFF2D322C),
    onPrimary: Color(0xFF0A390F),
    onPrimaryContainer: Color(0xFFBCF0B4),
    onSecondary: Color(0xFF253423),
    onSecondaryContainer: Color(0xFFD5E8CF),
    onSurface: Color(0xFFE0E4DB),
    onSurfaceVariant: Color(0xFFC2C9BD),
    onTertiary: Color(0xFF00363B),
    onTertiaryContainer: Color(0xFFBCEBF0),
    outline: Color(0xFF8C9388),
    outlineVariant: Color(0xFF424940),
    primary: Color(0xFFA1D39A),
    primaryContainer: Color(0xFF235024),
    scrim: Color(0xFF000000),
    secondary: Color(0xffbaccb3),
    secondaryContainer: Color(0xFF3B4B38),
    shadow: Color(0xFF000000),
    surface: Color(0xFF10140F),
    surfaceContainerHighest: Color(0xFF323630),
    surfaceTint: Color(0xFFA1D39A),
    tertiary: Color(0xFFA0CFD4),
    tertiaryContainer: Color(0xFF1F4D52),
  ),
  inputDecorationTheme: const InputDecorationTheme(
    alignLabelWithHint: false,
    filled: false,
    floatingLabelAlignment: FloatingLabelAlignment.start,
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    isCollapsed: false,
    isDense: false,
  ),
);
